### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by st-f** [aminography/RedirectGlide#1]
I'm getting this error:

> Output:  .../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1129: error: resource android:attr/fontVariationSettings not found.
.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1130: error: resource android:attr/ttcIndex not found.
error: failed linking references.

**Comment by aminography** [comment]
What is the `compileSdkVersion` in your app level `build.gradle`? This problem occurs when the app's `compileSdkVersion` differs with library. (for the library is 28)
